export const sampleQuestions = [
  {
    id: "edu-law-2013-01",
    year: "2013",
    type: "单项选择",
    topic: "教育法规",
    stem: "下列哪一项更符合义务教育阶段适龄儿童、少年入学保障的基本原则？",
    options: [
      { key: "A", text: "学校可根据成绩筛选入学对象" },
      { key: "B", text: "地方政府应保障适龄儿童、少年就近入学" },
      { key: "C", text: "监护人可自行决定是否履行入学义务" },
      { key: "D", text: "民办学校不受基本教育法规约束" },
    ],
    answer: "B",
    explanation:
      "义务教育强调政府保障、免试就近入学和适龄儿童少年接受教育的权利。备考时可把关键词记为“政府保障、免试、就近、适龄”。",
    sourceRef: "练功讲解样本 · 教育法规",
    xp: 16,
    coins: 10,
    difficulty: 1,
    enemy: "律令心魔",
    realm: "2013 入门秘境",
    drops: ["书页"],
  },
  {
    id: "psych-2014-02",
    year: "2014",
    type: "单项选择",
    topic: "教育心理学",
    stem: "学生能把新知识和已有经验建立联系，并主动整理成自己的理解，这更接近哪种学习方式？",
    options: [
      { key: "A", text: "机械学习" },
      { key: "B", text: "接受学习" },
      { key: "C", text: "有意义学习" },
      { key: "D", text: "过度学习" },
    ],
    answer: "C",
    explanation:
      "有意义学习强调新旧知识之间的实质性联系。看到“已有经验、主动联系、理解结构”时，优先想到有意义学习。",
    sourceRef: "练功讲解样本 · 教育心理学",
    xp: 18,
    coins: 12,
    difficulty: 2,
    enemy: "观心心魔",
    realm: "2014 观心林",
    drops: ["书页", "星砂"],
  },
  {
    id: "pedagogy-2016-03",
    year: "2016",
    type: "多项选择",
    topic: "教学设计",
    stem: "编写教案时，通常需要重点考虑哪些因素？",
    options: [
      { key: "A", text: "教学目标和重难点" },
      { key: "B", text: "学生已有基础" },
      { key: "C", text: "教学活动与评价方式" },
      { key: "D", text: "教师个人喜好优先于课程标准" },
    ],
    answer: "ABC",
    explanation:
      "教案要围绕目标、学情、活动、评价和资源组织。多选题可先排除明显违背课程标准或学生中心原则的选项。",
    sourceRef: "练功讲解样本 · 教学设计",
    xp: 22,
    coins: 14,
    difficulty: 3,
    enemy: "授业心魔",
    realm: "2016 授业工坊",
    drops: ["书页", "星砂", "墨玉"],
  },
  {
    id: "ethics-2018-04",
    year: "2018",
    type: "判断题",
    topic: "教师职业道德",
    stem: "教师职业道德只约束课堂教学行为，不涉及课外与家校沟通。",
    options: [
      { key: "A", text: "正确" },
      { key: "B", text: "错误" },
    ],
    answer: "B",
    explanation:
      "教师职业道德覆盖教育教学、师生关系、家校沟通和社会交往等多个场景，并不局限于课堂。",
    sourceRef: "练功讲解样本 · 教师职业道德",
    xp: 14,
    coins: 9,
    difficulty: 1,
    enemy: "师德心魔",
    realm: "2018 师德试炼",
    drops: ["书页"],
  },
  {
    id: "classroom-2021-05",
    year: "2021",
    type: "单项选择",
    topic: "班级管理",
    stem: "班主任在处理突发冲突时，最应优先做到的是哪一项？",
    options: [
      { key: "A", text: "立即公开批评冲突双方" },
      { key: "B", text: "先稳定情绪并保障学生安全" },
      { key: "C", text: "只听成绩较好的学生陈述" },
      { key: "D", text: "把处理结果完全交给家长决定" },
    ],
    answer: "B",
    explanation:
      "突发事件处理先看安全与情绪稳定，再调查事实、沟通教育和持续跟进。题干出现“突发冲突”时，优先抓安全底线。",
    sourceRef: "练功讲解样本 · 班级管理",
    xp: 20,
    coins: 12,
    difficulty: 2,
    enemy: "统御心魔",
    realm: "2021 统御迷阵",
    drops: ["书页", "星砂"],
  },
  {
    id: "child-2022-06",
    year: "2022",
    type: "单项选择",
    topic: "儿童发展",
    stem: "小学生情绪容易受情境影响，但调节能力正在发展。教师更适合采用哪种方式支持他们？",
    options: [
      { key: "A", text: "忽略情绪，只关注结果" },
      { key: "B", text: "要求学生立即独立解决所有情绪问题" },
      { key: "C", text: "提供具体表达方式和逐步调节策略" },
      { key: "D", text: "把情绪波动都归因于品德问题" },
    ],
    answer: "C",
    explanation:
      "儿童情绪稳定性和自控能力仍在发展。有效支持应具体、可操作，并帮助学生逐步形成表达和调节能力。",
    sourceRef: "练功讲解样本 · 儿童发展",
    xp: 18,
    coins: 11,
    difficulty: 2,
    enemy: "童心心魔",
    realm: "2022 童心谷",
    drops: ["书页", "灵签"],
  },
];
