export const assetManifest = {
  "mockup.world": "./docs/mockups/final-world-map.png",
  "mockup.story": "./docs/mockups/final-story-dialogue.png",
  "mockup.training": "./docs/mockups/final-training.png",
  "mockup.battle": "./docs/mockups/final-battle.png",
  "mockup.mindDemon": "./docs/mockups/final-mind-demon.png",
  "mockup.report": "./docs/mockups/final-report-growth.png",
  "mockup.daily": "./docs/mockups/final-daily.png",
  "mockup.rosterArtifacts": "./docs/mockups/final-roster-artifacts.png",
  "mockup.mobile.world": "./docs/mockups/mobile-world-map-ai-generated.png",
  "mockup.mobile.story": "./docs/mockups/mobile-story-dialogue-ai-generated.png",
  "mockup.mobile.training": "./docs/mockups/mobile-training-ai-generated.png",
  "mockup.mobile.battle": "./docs/mockups/mobile-battle-ai-generated.png",
  "mockup.mobile.mindDemon": "./docs/mockups/mobile-mind-demon-ai-generated.png",
  "mockup.mobile.report": "./docs/mockups/mobile-report-growth-ai-generated.png",
  "mockup.mobile.daily": "./docs/mockups/mobile-daily-ai-generated.png",
  "mockup.mobile.rosterArtifacts": "./docs/mockups/mobile-roster-artifacts-ai-generated.png",

  "bg.world": "./assets/generated/backgrounds/world-map.png",
  "bg.battle": "./assets/generated/backgrounds/battle-bg.png",
  "bg.academyGate": "./assets/generated/backgrounds/scenes/bg-academy-gate.png",
  "bg.training": "./assets/generated/backgrounds/scenes/bg-training.png",
  "bg.demonCorridor": "./assets/generated/backgrounds/scenes/bg-demon-corridor.png",
  "bg.night": "./assets/generated/backgrounds/scenes/bg-night.png",
  "bg.blackInk": "./assets/generated/backgrounds/scenes/bg-black-ink.png",
  "bg.daily": "./assets/generated/backgrounds/scenes/bg-daily.png",
  "bg.roster": "./assets/generated/backgrounds/scenes/bg-roster.png",
  "bg.chapter.law": "./assets/generated/backgrounds/chapters/bg-chapter-law.png",
  "bg.chapter.psychology": "./assets/generated/backgrounds/chapters/bg-chapter-psychology.png",
  "bg.chapter.design": "./assets/generated/backgrounds/chapters/bg-chapter-design.png",
  "bg.chapter.ethics": "./assets/generated/backgrounds/chapters/bg-chapter-ethics.png",
  "bg.chapter.classroom": "./assets/generated/backgrounds/chapters/bg-chapter-classroom.png",
  "bg.chapter.child": "./assets/generated/backgrounds/chapters/bg-chapter-child.png",
  "logo.academy": "./assets/generated/brand/logo-xiaoming-academy.png",

  "standee.mingche": "./assets/generated/characters/standees/cutouts/standee-mingche-cutout.png",
  "standee.azhi": "./assets/generated/characters/standees/cutouts/standee-azhi-cutout.png",
  "standee.qinglan": "./assets/generated/characters/standees/cutouts/standee-qinglan-cutout.png",
  "standee.xiaomo": "./assets/generated/characters/standees/cutouts/standee-xiaomo-cutout.png",

  "avatar.mingche": "./assets/generated/characters/avatars/avatar-mingche.png",
  "avatar.azhi": "./assets/generated/characters/avatars/avatar-azhi.png",
  "avatar.qinglan": "./assets/generated/characters/avatars/avatar-qinglan.png",
  "avatar.xiaomo": "./assets/generated/characters/avatars/avatar-xiaomo.png",

  "demon.law": "./assets/generated/demons/demon-law.png",
  "demon.psych": "./assets/generated/demons/demon-psych.png",
  "demon.design": "./assets/generated/demons/demon-design.png",
  "demon.ethics": "./assets/generated/demons/demon-ethics.png",
  "demon.classroom": "./assets/generated/demons/demon-classroom.png",
  "demon.child": "./assets/generated/demons/demon-child.png",
  "demon.mixed": "./assets/generated/demons/demon-mixed.png",

  "item.shuye": "./assets/generated/items/item-shuye.png",
  "item.xingsha": "./assets/generated/items/item-xingsha.png",
  "item.moyu": "./assets/generated/items/item-moyu.png",
  "item.lingqian": "./assets/generated/items/item-lingqian.png",

  "artifact.biling": "./assets/generated/artifacts/fazhi-biling.png",
  "artifact.yanling": "./assets/generated/artifacts/fazhi-yanling.png",
  "artifact.zhiling": "./assets/generated/artifacts/fazhi-zhiling.png",
  "artifact.moling": "./assets/generated/artifacts/fazhi-moling.png",

  "node.normal": "./assets/generated/nodes/node-normal.png",
  "node.elite": "./assets/generated/nodes/node-elite.png",
  "node.recover": "./assets/generated/nodes/node-recover.png",
  "node.treasure": "./assets/generated/nodes/node-treasure.png",
  "node.demon": "./assets/generated/nodes/node-demon.png",
  "node.mystery": "./assets/generated/nodes/node-mystery.png",
  "node.resonance": "./assets/generated/nodes/node-resonance.png",
  "node.trial": "./assets/generated/nodes/node-trial.png",

  "seal.locked": "./assets/generated/seals/seal-locked.png",
  "seal.unlocked": "./assets/generated/seals/seal-unlocked.png",
  "seal.glowing": "./assets/generated/seals/seal-glowing.png",
  "ink.mark": "./assets/generated/brand/ink-mark.png",

  "ui.shell.hud.desktop.textless": "./assets/generated/ui/shell/mockup-hud-desktop-textless-alpha.png",
  "ui.shell.hud.mobile.textless": "./assets/generated/ui/shell/mockup-hud-mobile-textless-alpha.png",
  "ui.nav.desktop.textless": "./assets/generated/ui/nav/mockup-bottom-nav-desktop-alpha.png",
  "ui.nav.mobile.textless": "./assets/generated/ui/nav/mockup-bottom-nav-mobile-alpha.png",
  "ui.panels.parchment.sheet": "./assets/generated/ui/mockup-panels/parchment-panel-sheet-alpha.png",
  "ui.panels.dark.sheet": "./assets/generated/ui/mockup-panels/dark-panel-sheet-alpha.png",
  "map.mockup.components.sheet": "./assets/generated/map/mockup-components/world-map-components-alpha.png",
  "story.mockup.components.sheet": "./assets/generated/story/mockup-components/story-components-alpha.png",
  "training.mockup.components.sheet": "./assets/generated/training/mockup-components/training-components-alpha.png",
  "battle.mockup.components.sheet": "./assets/generated/battle/mockup-components/battle-components-alpha.png",
  "mindDemon.mockup.components.sheet": "./assets/generated/mind-demon/mockup-components/mind-demon-components-alpha.png",
  "report.mockup.components.sheet": "./assets/generated/report/mockup-components/report-components-alpha.png",
  "daily.mockup.components.sheet": "./assets/generated/daily/mockup-components/daily-components-alpha.png",
  "roster.mockup.components.sheet": "./assets/generated/roster/mockup-components/roster-artifact-components-alpha.png",
  "characters.mockup.uiVariants.sheet": "./assets/generated/characters/mockup-variants/character-ui-variants-alpha.png",
  "items.mockup.iconSheet": "./assets/generated/items/mockup-components/item-artifact-icon-sheet-alpha.png",
  "characters.mockup.mingche.bust": "./assets/generated/characters/mockup-variants/split/mingche-bust.png",
  "characters.mockup.mingche.half": "./assets/generated/characters/mockup-variants/split/mingche-half.png",
  "characters.mockup.mingche.avatar": "./assets/generated/characters/mockup-variants/split/mingche-avatar.png",
  "characters.mockup.azhi.bust": "./assets/generated/characters/mockup-variants/split/azhi-bust.png",
  "characters.mockup.azhi.half": "./assets/generated/characters/mockup-variants/split/azhi-half.png",
  "characters.mockup.azhi.avatar": "./assets/generated/characters/mockup-variants/split/azhi-avatar.png",
  "characters.mockup.qinglan.bust": "./assets/generated/characters/mockup-variants/split/qinglan-bust.png",
  "characters.mockup.qinglan.half": "./assets/generated/characters/mockup-variants/split/qinglan-half.png",
  "characters.mockup.qinglan.avatar": "./assets/generated/characters/mockup-variants/split/qinglan-avatar.png",
  "characters.mockup.xiaomo.bust": "./assets/generated/characters/mockup-variants/split/xiaomo-bust.png",
  "characters.mockup.xiaomo.half": "./assets/generated/characters/mockup-variants/split/xiaomo-half.png",
  "characters.mockup.xiaomo.avatar": "./assets/generated/characters/mockup-variants/split/xiaomo-avatar.png",
  "items.mockup.currency.starSand": "./assets/generated/items/mockup-components/split/currency-star-sand.png",
  "items.mockup.currency.spiritPage": "./assets/generated/items/mockup-components/split/currency-spirit-page.png",
  "items.mockup.material.inkJade": "./assets/generated/items/mockup-components/split/material-ink-jade.png",
  "items.mockup.artifact.heartToken": "./assets/generated/items/mockup-components/split/artifact-heart-token.png",
  "items.mockup.artifact.lotusToken": "./assets/generated/items/mockup-components/split/artifact-lotus-token.png",
  "items.mockup.artifact.brush": "./assets/generated/items/mockup-components/split/artifact-brush.png",
  "items.mockup.artifact.bell": "./assets/generated/items/mockup-components/split/artifact-bell.png",
  "items.mockup.artifact.medallion": "./assets/generated/items/mockup-components/split/artifact-medallion.png",
  "items.mockup.artifact.mirror": "./assets/generated/items/mockup-components/split/artifact-mirror.png",
  "items.mockup.artifact.book": "./assets/generated/items/mockup-components/split/artifact-book.png",
  "items.mockup.reward.sparkBurst": "./assets/generated/items/mockup-components/split/reward-spark-burst.png",
  "items.mockup.material.stone": "./assets/generated/items/mockup-components/split/material-stone.png",
  "items.mockup.material.scroll": "./assets/generated/items/mockup-components/split/material-scroll.png",
  "items.mockup.reward.lotus": "./assets/generated/items/mockup-components/split/lotus-reward.png",
  "items.mockup.rarity.common": "./assets/generated/items/mockup-components/split/rarity-gem-common.png",
  "items.mockup.rarity.rare": "./assets/generated/items/mockup-components/split/rarity-gem-rare.png",
  "items.mockup.rarity.epic": "./assets/generated/items/mockup-components/split/rarity-gem-epic.png",
  "items.mockup.rarity.legendary": "./assets/generated/items/mockup-components/split/rarity-gem-legendary.png",
  "items.mockup.reward.chestToken": "./assets/generated/items/mockup-components/split/reward-chest-token.png",
};

export const requiredAssetIds = [
  "mockup.world",
  "mockup.story",
  "mockup.training",
  "mockup.battle",
  "mockup.mindDemon",
  "mockup.report",
  "mockup.daily",
  "mockup.rosterArtifacts",
  "mockup.mobile.world",
  "mockup.mobile.story",
  "mockup.mobile.training",
  "mockup.mobile.battle",
  "mockup.mobile.mindDemon",
  "mockup.mobile.report",
  "mockup.mobile.daily",
  "mockup.mobile.rosterArtifacts",
  "bg.world",
  "bg.battle",
  "bg.academyGate",
  "bg.training",
  "bg.demonCorridor",
  "bg.night",
  "bg.blackInk",
  "bg.daily",
  "bg.roster",
  "bg.chapter.law",
  "bg.chapter.psychology",
  "bg.chapter.design",
  "bg.chapter.ethics",
  "bg.chapter.classroom",
  "bg.chapter.child",
  "logo.academy",
  "standee.mingche",
  "standee.azhi",
  "standee.qinglan",
  "standee.xiaomo",
  "avatar.mingche",
  "avatar.azhi",
  "avatar.qinglan",
  "avatar.xiaomo",
  "demon.law",
  "demon.psych",
  "demon.design",
  "demon.ethics",
  "demon.classroom",
  "demon.child",
  "demon.mixed",
  "item.shuye",
  "item.xingsha",
  "item.moyu",
  "item.lingqian",
  "artifact.biling",
  "artifact.yanling",
  "artifact.zhiling",
  "artifact.moling",
  "node.normal",
  "node.elite",
  "node.recover",
  "node.treasure",
  "node.demon",
  "node.mystery",
  "node.resonance",
  "node.trial",
  "seal.locked",
  "seal.unlocked",
  "seal.glowing",
  "ink.mark",
  "ui.shell.hud.desktop.textless",
  "ui.shell.hud.mobile.textless",
  "ui.nav.desktop.textless",
  "ui.nav.mobile.textless",
  "ui.panels.parchment.sheet",
  "ui.panels.dark.sheet",
  "map.mockup.components.sheet",
  "story.mockup.components.sheet",
  "training.mockup.components.sheet",
  "battle.mockup.components.sheet",
  "mindDemon.mockup.components.sheet",
  "report.mockup.components.sheet",
  "daily.mockup.components.sheet",
  "roster.mockup.components.sheet",
  "characters.mockup.uiVariants.sheet",
  "items.mockup.iconSheet",
  "characters.mockup.mingche.bust",
  "characters.mockup.mingche.half",
  "characters.mockup.mingche.avatar",
  "characters.mockup.azhi.bust",
  "characters.mockup.azhi.half",
  "characters.mockup.azhi.avatar",
  "characters.mockup.qinglan.bust",
  "characters.mockup.qinglan.half",
  "characters.mockup.qinglan.avatar",
  "characters.mockup.xiaomo.bust",
  "characters.mockup.xiaomo.half",
  "characters.mockup.xiaomo.avatar",
  "items.mockup.currency.starSand",
  "items.mockup.currency.spiritPage",
  "items.mockup.material.inkJade",
  "items.mockup.artifact.heartToken",
  "items.mockup.artifact.lotusToken",
  "items.mockup.artifact.brush",
  "items.mockup.artifact.bell",
  "items.mockup.artifact.medallion",
  "items.mockup.artifact.mirror",
  "items.mockup.artifact.book",
  "items.mockup.reward.sparkBurst",
  "items.mockup.material.stone",
  "items.mockup.material.scroll",
  "items.mockup.reward.lotus",
  "items.mockup.rarity.common",
  "items.mockup.rarity.rare",
  "items.mockup.rarity.epic",
  "items.mockup.rarity.legendary",
  "items.mockup.reward.chestToken",
];

export function getAssetPath(id) {
  const path = assetManifest[id];
  if (!path) throw new Error(`Unknown asset id: ${id}`);
  return path;
}
